// <auto-generated />
using System;
using BLL.repoistory;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BLL.Migrations
{
    [DbContext(typeof(SQLDbContext))]
    [Migration("20190803120357_2002")]
    partial class _2002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BLL.Email", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("EmailHasValidated");

                    b.Property<int>("OwnerId");

                    b.Property<string>("ValidationCode");

                    b.HasKey("id");

                    b.ToTable("emails");
                });

            modelBuilder.Entity("BLL.entity.Articled.Blog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishSuggestDateTime");

                    b.Property<string>("Title");

                    b.HasKey("id");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("BLL.entity.Articled.BlogToKeywords", b =>
                {
                    b.Property<int>("BlogId");

                    b.Property<int>("KeywordId");

                    b.HasKey("BlogId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("BlogToKeywords");
                });

            modelBuilder.Entity("BLL.entity.Articled.Keyword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PublishSuggestDateTime");

                    b.Property<string>("Title");

                    b.HasKey("id");

                    b.ToTable("Keyword");
                });

            modelBuilder.Entity("BLL.entity.Articled.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Context");

                    b.Property<DateTime>("PublishMessageTime");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("BLL.entity.Articled.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<int>("PostId");

                    b.Property<string>("Title");

                    b.HasKey("id");

                    b.HasIndex("BlogId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BLL.MYUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Emailid");

                    b.Property<int?>("InvitedByid");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.HasKey("id");

                    b.HasIndex("Emailid");

                    b.HasIndex("InvitedByid");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BLL.Suggest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutherId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("PublishSuggestDateTime");

                    b.Property<string>("Title");

                    b.HasKey("id");

                    b.ToTable("Suggests");
                });

            modelBuilder.Entity("BLL.entity.Articled.BlogToKeywords", b =>
                {
                    b.HasOne("BLL.entity.Articled.Blog", "Blog")
                        .WithMany("Keywords")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BLL.entity.Articled.Keyword", "Keyword")
                        .WithMany("Blogs")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BLL.entity.Articled.Post", b =>
                {
                    b.HasOne("BLL.entity.Articled.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BLL.MYUser", b =>
                {
                    b.HasOne("BLL.Email", "Email")
                        .WithMany()
                        .HasForeignKey("Emailid");

                    b.HasOne("BLL.MYUser", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByid");
                });
#pragma warning restore 612, 618
        }
    }
}
